import { api, LightningElement } from 'lwc';
import { FlowAttributeChangeEvent, FlowNavigationNextEvent, FlowNavigationBackEvent } from 'lightning/flowSupport';

const AUDIO_TYPES_REQUIRED_HEADERS = ['Audio Type(s) Required', 'Audio_Type_s_Required__c', 'Headset Audio Type'];

// Columns whose name is identical across all CSV template versions.
const FIXED_REQUIRED_HEADERS = [
    'Opportunity Site Id',
    'Number of Cameras',
    'Point of Sale System',
    'NVR DVR Make',
    'NVR DVR Model',
    'Camera Make',
    'Camera Model',
    'Additional billing notes',
    'NVR DVR Username',
    'NVR DVR Password',
    'NVR DVR Record In Parallel With SRD',
    'NVR DVR Required as POE',
    'Permission to Reset NVR and Cameras',
    'HME Type',
    'HME Username',
    'HME Password',
    'Zoom IP',
    'Site Open Date'
];

// Columns that have different names depending on which CSV template version was used.
// The upload component accepts both the format generated by opportunitySiteTemplateDownload
// and the legacy format used by older exported templates.
// Each entry: { key: fieldKey, variants: [primaryName, ...legacyNames] }
const COLUMN_ALIASES = [
    {
        key: 'dataIntegrationsRequiredOther',
        variants: ['Data integrations required other', 'Data integrations required']
    },
    { key: 'shippingAddressStreet', variants: ['Shipping Address Street', 'Shipping Address (Street)'] },
    { key: 'shippingAddressCity', variants: ['Shipping Address City', 'Shipping Address (City)'] },
    {
        key: 'shippingAddressStateCode',
        variants: ['Shipping Address State Code', 'Shipping Address (State/Province)']
    },
    {
        key: 'shippingAddressPostalCode',
        variants: ['Shipping Address Postal Code', 'Shipping Address (ZIP/Postal Code)']
    },
    {
        key: 'shippingAddressCountryCode',
        variants: ['Shipping Address Country Code', 'Shipping Address (Country/Territory)']
    },
    { key: 'whoIsInstalling', variants: ['Who is Installing', 'Who is Installing?'] },
    { key: 'siteAddressStreet', variants: ['Street', 'Site Address (Street)'] },
    { key: 'siteAddressCity', variants: ['City', 'Site Address (City)'] },
    { key: 'siteAddressStateCode', variants: ['State Code', 'Site Address (State/Province)'] },
    { key: 'siteAddressPostalCode', variants: ['Postal Code', 'Site Address (ZIP/Postal Code)'] },
    { key: 'siteAddressCountryCode', variants: ['Country Code', 'Site Address (Country/Territory)'] }
];

// Required value checks per data row. Mirrors REQUIRED_FIELDS in
// opportunitySiteCameraTable.js but limited to columns present in the CSV template
// (contact lookups and headsetAudioType are not in the CSV, so they are excluded).
const REQUIRED_VALUE_FIELDS = [
    { key: 'siteAddressStreet', label: 'Site Address Street' },
    { key: 'siteAddressCity', label: 'Site Address City' },
    { key: 'siteAddressStateCode', label: 'Site Address State Code' },
    { key: 'siteAddressPostalCode', label: 'Site Address Postal Code' },
    { key: 'siteAddressCountryCode', label: 'Site Address Country Code' },
    { key: 'totalCamera', label: 'Number of Cameras' },
    { key: 'pointOfSaleSystem', label: 'Point of Sale System' },
    { key: 'cameraMakeCustom', label: 'Camera Make' },
    { key: 'cameraModelCustom', label: 'Camera Model' },
    { key: 'dataIntegrationsRequiredOther', label: 'Data Integrations Required Other' },
    { key: 'whoIsInstalling', label: 'Who is Installing' },
    { key: 'additionalBillingNotes', label: 'Additional Billing Notes' },
    { key: 'shippingAddressStreet', label: 'Shipping Address Street' },
    { key: 'shippingAddressCity', label: 'Shipping Address City' },
    { key: 'shippingAddressStateCode', label: 'Shipping Address State Code' },
    { key: 'shippingAddressPostalCode', label: 'Shipping Address Postal Code' },
    { key: 'shippingAddressCountryCode', label: 'Shipping Address Country Code' },
    { key: 'siteOpenDate', label: 'Site Open Date' },
    // NVR/DVR details are only required when NVR DVR Required as POE is true
    { key: 'cameraMake', label: 'NVR DVR Make', condition: (row) => row.nvrDvrRequiredAsPoe === true },
    { key: 'cameraModel', label: 'NVR DVR Model', condition: (row) => row.nvrDvrRequiredAsPoe === true },
    { key: 'nvrDvrUsername', label: 'NVR DVR Username', condition: (row) => row.nvrDvrRequiredAsPoe === true },
    { key: 'nvrDvrPassword', label: 'NVR DVR Password', condition: (row) => row.nvrDvrRequiredAsPoe === true }
    // Headset/HME details (HME Type, Audio Type(s) Required, HME Username, HME Password) are optional
];

export default class OpportunitySiteTemplateUpload extends LightningElement {
    @api updatesJson;

    errorMessage;
    validationErrors = [];
    fileName;
    rowCount = 0;

    get hasError() {
        return !!(this.errorMessage || this.validationErrors.length > 0);
    }

    get hasValidationErrors() {
        return this.validationErrors.length > 0;
    }

    handleFileChange(event) {
        this.errorMessage = undefined;
        this.validationErrors = [];
        this.fileName = undefined;
        this.rowCount = 0;
        this.publishUpdates([]);

        const file = event.target.files && event.target.files[0];
        if (!file) {
            return;
        }

        this.fileName = file.name;
        const reader = new FileReader();
        reader.onload = () => {
            try {
                const text = reader.result;
                const { rows, validationErrors } = this.parseCsv(text);
                if (validationErrors.length > 0) {
                    this.validationErrors = validationErrors;
                    this.publishUpdates([]);
                    this.rowCount = 0;
                    return;
                }
                this.rowCount = rows.length;
                this.publishUpdates(rows);
            } catch (error) {
                this.errorMessage = error.message || 'Unable to parse the uploaded CSV template.';
                this.publishUpdates([]);
                this.rowCount = 0;
            }
        };
        reader.onerror = () => {
            this.errorMessage = 'Unable to read the uploaded file.';
            this.publishUpdates([]);
        };
        reader.readAsText(file);
    }

    get cannotProceed() {
        return this.hasError || !this.rowCount;
    }

    handleNext() {
        if (this.cannotProceed) {
            return;
        }
        this.dispatchEvent(new FlowNavigationNextEvent());
    }

    handlePrevious() {
        this.dispatchEvent(new FlowNavigationBackEvent());
    }

    @api
    validate() {
        if (this.errorMessage || this.validationErrors.length > 0) {
            return { isValid: false, errorMessage: 'Resolve the error(s) shown above before continuing.' };
        }
        if (!this.rowCount) {
            return {
                isValid: false,
                errorMessage: 'Upload a completed CSV template before continuing.'
            };
        }
        return { isValid: true };
    }

    parseCsv(text) {
        const normalizedText = (text || '').replace(/^\uFEFF/, '').trim();
        if (!normalizedText) {
            throw new Error('The uploaded CSV file is empty.');
        }

        const lines = normalizedText.split(/\r?\n/).filter((line) => line.trim() !== '');
        if (lines.length < 2) {
            throw new Error('The uploaded CSV file does not contain any data rows.');
        }

        const headers = this.parseCsvLine(lines[0]).map((header) => header.trim());

        // Collect all missing required columns at once before reporting.
        const missingHeaders = FIXED_REQUIRED_HEADERS.filter((header) => !headers.includes(header));

        // For aliased columns, resolve which variant name is present in this CSV.
        // If no variant is found, report the primary (first) name as missing.
        const resolvedAliases = {};
        COLUMN_ALIASES.forEach((alias) => {
            const found = alias.variants.find((v) => headers.includes(v));
            if (found) {
                resolvedAliases[alias.key] = found;
            } else {
                missingHeaders.push(alias.variants[0]);
            }
        });

        const audioTypesRequiredHeader = AUDIO_TYPES_REQUIRED_HEADERS.find((header) => headers.includes(header));
        if (!audioTypesRequiredHeader) {
            missingHeaders.push(`one of: ${AUDIO_TYPES_REQUIRED_HEADERS.join(', ')}`);
        }
        if (missingHeaders.length > 0) {
            throw new Error(
                `The uploaded CSV file is missing the following column(s): ${missingHeaders.join('; ')}.`
            );
        }

        const headerIndex = {};
        headers.forEach((header, index) => {
            headerIndex[header] = index;
        });

        const col = (key) => resolvedAliases[key];

        const typeErrors = [];
        const rows = lines
            .slice(1)
            .map((line) => this.parseCsvLine(line))
            .filter((columns) => columns.some((value) => value.trim() !== ''))
            .map((columns, idx) => {
                const siteName = this.readColumn(columns, headerIndex, 'Site Name');
                const rowLabel = `Row ${idx + 2}${siteName ? ` (${siteName})` : ''}`;

                const totalCamera = this.parseNumberSafe(
                    this.readColumn(columns, headerIndex, 'Number of Cameras'),
                    rowLabel,
                    'Number of Cameras',
                    typeErrors
                );
                const nvrDvrRecordInParallelWithSrd = this.parseBooleanSafe(
                    this.readColumn(columns, headerIndex, 'NVR DVR Record In Parallel With SRD'),
                    rowLabel,
                    'NVR DVR Record In Parallel With SRD',
                    typeErrors
                );
                const nvrDvrRequiredAsPoe = this.parseBooleanSafe(
                    this.readColumn(columns, headerIndex, 'NVR DVR Required as POE'),
                    rowLabel,
                    'NVR DVR Required as POE',
                    typeErrors
                );
                const permissionToResetNvrAndCameras = this.parseBooleanSafe(
                    this.readColumn(columns, headerIndex, 'Permission to Reset NVR and Cameras'),
                    rowLabel,
                    'Permission to Reset NVR and Cameras',
                    typeErrors
                );
                const siteOpenDate = this.parseDateSafe(
                    this.readColumn(columns, headerIndex, 'Site Open Date'),
                    rowLabel,
                    typeErrors
                );

                return {
                    siteName,
                    rowLabel,
                    opportunitySiteId: this.readColumn(columns, headerIndex, 'Opportunity Site Id'),
                    totalCamera,
                    pointOfSaleSystem: this.readColumn(columns, headerIndex, 'Point of Sale System'),
                    cameraMake: this.readColumn(columns, headerIndex, 'NVR DVR Make'),
                    cameraModel: this.readColumn(columns, headerIndex, 'NVR DVR Model'),
                    cameraMakeCustom: this.readColumn(columns, headerIndex, 'Camera Make'),
                    cameraModelCustom: this.readColumn(columns, headerIndex, 'Camera Model'),
                    dataIntegrationsRequiredOther: this.readColumn(columns, headerIndex, col('dataIntegrationsRequiredOther')),
                    shippingAddressStreet: this.readColumn(columns, headerIndex, col('shippingAddressStreet')),
                    shippingAddressCity: this.readColumn(columns, headerIndex, col('shippingAddressCity')),
                    shippingAddressStateCode: this.readColumn(columns, headerIndex, col('shippingAddressStateCode')),
                    shippingAddressPostalCode: this.readColumn(columns, headerIndex, col('shippingAddressPostalCode')),
                    shippingAddressCountryCode: this.readColumn(columns, headerIndex, col('shippingAddressCountryCode')),
                    whoIsInstalling: this.readColumn(columns, headerIndex, col('whoIsInstalling')),
                    additionalBillingNotes: this.readColumn(columns, headerIndex, 'Additional billing notes'),
                    nvrDvrUsername: this.readColumn(columns, headerIndex, 'NVR DVR Username'),
                    nvrDvrPassword: this.readColumn(columns, headerIndex, 'NVR DVR Password'),
                    nvrDvrRecordInParallelWithSrd,
                    nvrDvrRequiredAsPoe,
                    permissionToResetNvrAndCameras,
                    audioTypesRequired: this.readColumn(columns, headerIndex, audioTypesRequiredHeader),
                    hmeType: this.readColumn(columns, headerIndex, 'HME Type'),
                    hmeUsername: this.readColumn(columns, headerIndex, 'HME Username'),
                    hmePassword: this.readColumn(columns, headerIndex, 'HME Password'),
                    zoomIp: this.readColumn(columns, headerIndex, 'Zoom IP'),
                    siteAddressStreet: this.readColumn(columns, headerIndex, col('siteAddressStreet')),
                    siteAddressCity: this.readColumn(columns, headerIndex, col('siteAddressCity')),
                    siteAddressStateCode: this.readColumn(columns, headerIndex, col('siteAddressStateCode')),
                    siteAddressPostalCode: this.readColumn(columns, headerIndex, col('siteAddressPostalCode')),
                    siteAddressCountryCode: this.readColumn(columns, headerIndex, col('siteAddressCountryCode')),
                    siteOpenDate
                };
            })
            .filter((row) => row.opportunitySiteId);

        if (typeErrors.length > 0) {
            throw new Error(`Found ${typeErrors.length} format error(s):\n${typeErrors.join('\n')}`);
        }

        const validationErrors = this.validateRequiredValues(rows);
        return { rows, validationErrors };
    }

    validateRequiredValues(rows) {
        const errorsByRow = [];
        rows.forEach((row) => {
            const missingFields = REQUIRED_VALUE_FIELDS.filter((field) => {
                if (field.condition && !field.condition(row)) {
                    return false;
                }
                const value = row[field.key];
                return value === null || value === undefined || value === '';
            }).map((field) => field.label);

            if (missingFields.length > 0) {
                errorsByRow.push({ rowLabel: row.rowLabel, missingFields });
            }
        });
        return errorsByRow;
    }

    parseCsvLine(line) {
        const values = [];
        let currentValue = '';
        let inQuotes = false;

        for (let i = 0; i < line.length; i += 1) {
            const character = line[i];

            if (character === '"') {
                if (inQuotes && line[i + 1] === '"') {
                    currentValue += '"';
                    i += 1;
                } else {
                    inQuotes = !inQuotes;
                }
            } else if (character === ',' && !inQuotes) {
                values.push(currentValue);
                currentValue = '';
            } else {
                currentValue += character;
            }
        }

        values.push(currentValue);
        return values;
    }

    readColumn(columns, headerIndex, headerName) {
        const index = headerIndex[headerName];
        return index === undefined || columns[index] === undefined ? '' : columns[index].trim();
    }

    parseNumberSafe(rawValue, rowLabel, fieldLabel, errors) {
        if (!rawValue) {
            return null;
        }
        const parsedValue = Number(rawValue);
        if (Number.isNaN(parsedValue)) {
            errors.push(`${rowLabel}: Invalid number value "${rawValue}" in "${fieldLabel}".`);
            return null;
        }
        return parsedValue;
    }

    parseBooleanSafe(rawValue, rowLabel, fieldLabel, errors) {
        const normalizedValue = (rawValue || '').trim().toLowerCase();
        if (!normalizedValue) {
            return false;
        }
        if (['true', 'yes', 'y', '1'].includes(normalizedValue)) {
            return true;
        }
        if (['false', 'no', 'n', '0'].includes(normalizedValue)) {
            return false;
        }
        errors.push(`${rowLabel}: Invalid checkbox value "${rawValue}" in "${fieldLabel}". Use TRUE or FALSE.`);
        return false;
    }

    parseDateSafe(rawValue, rowLabel, errors) {
        if (!rawValue) {
            return null;
        }
        const normalizedValue = rawValue.trim();
        if (!/^\d{4}-\d{2}-\d{2}$/.test(normalizedValue)) {
            errors.push(`${rowLabel}: Invalid date value "${rawValue}" in "Site Open Date". Use YYYY-MM-DD format.`);
            return null;
        }
        return normalizedValue;
    }

    publishUpdates(rows) {
        this.updatesJson = JSON.stringify(rows);
        this.dispatchEvent(new FlowAttributeChangeEvent('updatesJson', this.updatesJson));
    }
}